services:
  ros2base:
    build:
      context: base_images/ros_base
    image: ros_base:2509

  ros2yolobase:
    build:
      context: base_images/ros_yolo_base
    image: ros_yolo_base:2509
    depends_on:
      - ros2base
    platform: linux/amd64

x-bake:
  ros2base:
    platforms:
      - linux/amd64
      - linux/arm64

  ros2yolobase:
    platforms:
      - linux/amd64
