name: Build and Push YOLO to GHCR (AMD64)

on:
  push:
    branches: [main, 2509]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ros_yolo_base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=2509
          labels: |
            org.opencontainers.image.title=ros_yolo_base
            org.opencontainers.image.description=ROS YOLO base image for IoT workflows
            org.opencontainers.image.source=https://github.com/hsnlab-iot/ros_base
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./base_images/ros_yolo_base
          file: ./base_images/ros_yolo_base/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
